version: '2'

services:
  app:
    build: ./node
    ports:
      - "80:8080"
    environment:
      - REDIS_IP=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local
