version: '2'

services:
  consul:
    image: gliderlabs/consul-server:latest
    hostname: consul
    ports:
      - "8500:8500"
    command: -data-dir /tmp/consul -bootstrap -client 0.0.0.0

  registrator:
    image: gliderlabs/registrator:master
    hostname: registrator
    links:
      - consul:consul
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    command: -internal consul://consul:8500

  lb:
    image: chenglong/nginx-consul-template
    container_name: lb
    ports:
      - "80:80"
    environment:
      - SERVICE=myapp
    depends_on:
      - app
    links:
      - consul:consul

  app:
    build: ./node
    ports:
      - "8080"
    environment:
      - SERVICE_NAME=myapp
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local
